version: '3.9'

services:
  node:
      container_name: ${COMPOSE_PROJECT_NAME}-admin
      build: 
          context: ./node
          dockerfile: Dockerfile
      tty: true
      ports:
        # - 3000:3000
        # - 5173:5173
        # - 5050:5050
        # - 8081:8081
        - "8080:8080"
      volumes: 
          - ../:/var/project
      # command: ['npm', 'run', 'serve']   # ['npm', 'run', 'watch-poll']